FROM golang:1.14 as builder

LABEL maintainer="Alireza Josheghani <josheghani.dev@gmail.com>"

ARG DEBIAN_FRONTEND=noninteractive

# Choosing work directory
WORKDIR /code

# Adding project to work directory
ADD . /code

RUN mkdir /config

# build project
RUN go build -o server .

FROM alpine

WORKDIR /code

COPY --from=builder /config /config
COPY --from=builder /code/server .

EXPOSE 55283

ENTRYPOINT ["/code/server"]
CMD ["--port", "55283"]